MvcProjeKampi/Controllers/HeadingController.cs
using BusinessLogicLayer.Concrete;
using BusinessLogicLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());
        public ActionResult Index()
        {
            var headingValues = hm.GetList();
            return View(headingValues);
        }
        [HttpGet]
        public ActionResult AddHeading()
        {
            // dropdown içine dataları yüklüyor. Viewbag ile tasıma işlemi yapılıyor.
            List<SelectListItem> valueCategory = (from c in cm.GetList() select new SelectListItem { Text = c.CategoryName, Value = c.CategoryId.ToString() }).ToList();
            ViewBag.vlc = valueCategory;
            //


            List<SelectListItem> valueWriter = (from c in wm.GetList() select new SelectListItem { Text = c.WriterName + " " + c.WriterSurname, Value = c.WriterId.ToString() }).ToList();
            ViewBag.vlw = valueWriter;
            return View();
        }
        [HttpPost]
        public ActionResult AddHeading(Heading p)
        {
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            hm.HeadingAdd(p);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            // dropdown içine dataları yüklüyor. Viewbag ile tasıma işlemi yapılıyor.
            List<SelectListItem> valueCategory = (from c in cm.GetList() select new SelectListItem { Text = c.CategoryName, Value = c.CategoryId.ToString() }).ToList();
            ViewBag.vlc = valueCategory;
            //       

            var headingValue = hm.GetById(id);
            return View(headingValue);
        }
        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            hm.HeadingUpdate(p);
            return RedirectToAction("Index");

        }

        [HttpGet]
        public ActionResult DeleteHeading(int id)
        {
            var headingValue = hm.GetById(id);
            headingValue.HeadingStatus = false;
            hm.HeadingDelete(headingValue);

            return RedirectToAction("Index");
        }

    }
}

MvcProjeKampi/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>Yeni Başlık Ekleme</h2>

<br />

@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
        <br />
        @Html.Label("Yazar")
        @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterId)
        <br />
        <br />
        <button class="btn btn-info">Başlık Oluştur</button>
    </div>
}

MvcProjeKampi/Views/Heading/ContentByHeading.cshtml
@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            <div class="time-label">
                                <span class="bg-success">Tarih</span>
                            </div>
                            <!-- /.timeline-label -->
                            <!-- timeline item -->
                            <div>
                                <i class="fas fa-comment bg-yellow"></i>
                                <div class="timeline-item">
                                    <h3 class="timeline-header"><a href="#">Test</a> Deneme</h3>
                                    <div class="timeline-body">
                                        İçerik
                                    </div>
                                </div>
                            </div>
                            <!-- END timeline item -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MvcProjeKampi/Views/Heading/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlık Güncelleme Sayfası</h2>

<br />

@using (Html.BeginForm("EditHeading", "Heading",FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Başlık Id")
    @Html.TextBoxFor(x => x.HeadingId, new { @class = "form-control" })
    <br />
    @Html.Label("Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />
    @Html.Label("Yazar ID")
    @Html.TextBoxFor(x => x.WriterId, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
}

MvcProjeKampi/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    string color = "";
    string Statuscolor = "";
    string status = "";
    string ButonStatus = "";
    string ButonStatusColor = "";
}

<br />
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Başlık İşlemleri</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th style="width: 20%">
                            Başlık Adı
                        </th>
                        <th style="width: 15%">
                            Oluşturan Yazar
                        </th>
                        <th style="width: 10%">
                            Durum
                        </th>
                        <th style="width: 8%" class="text-center">
                            Kategori
                        </th>
                        <th style="width: 20%">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        if (item.Category.CategoryName == "Film")
                        {
                            color = "badge badge-danger";
                        }
                        if (item.Category.CategoryName == "Spor")
                        {
                            color = "badge badge-primary";
                        }
                        if (item.Category.CategoryName == "Eğitim")
                        {
                            color = "badge badge-info";
                        }
                        if (item.Category.CategoryName == "Kitap")
                        {
                            color = "badge badge-success";
                        }
                        if (item.Category.CategoryName == "Sosyal Media")
                        {
                            color = "badge badge-secondary";
                        }

                        if (item.HeadingStatus == true)
                        {
                            status = "Aktif";
                            ButonStatus = "Pasif Et";
                            Statuscolor = "badge badge-success";
                            ButonStatusColor = "btn btn-danger btn - sm";
                        }
                        if (item.HeadingStatus == false)
                        {
                            status = "Pasif";
                            ButonStatus = "Aktif Et";
                            ButonStatusColor = "btn btn-success btn - sm";
                            Statuscolor = "badge badge-danger";
                        }
                        <tr>
                            <td>
                                @item.HeadingId
                            </td>
                            <td>
                                <a>
                                    @item.HeadingName
                                </a>
                                <br />
                                <small>
                                    @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                </small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                    </li>
                                </ul>
                            </td>
                            <td>
                                <span class="@Statuscolor">@status</span>
                            </td>
                            <td class="project-state">
                                <span class="@color">@item.Category.CategoryName</span>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingId">
                                    <i class="fas fa-folder">
                                    </i>
                                    Yazılar
                                </a>
                                <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingId">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Düzenle
                                </a>
                                <a class="@ButonStatusColor" href="/Heading/DeleteHeading/@item.HeadingId">
                                    <i class="fas fa-trash">
                                    </i>
                                    @ButonStatus
                                </a>
                            </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
<br />
<a href="/Heading/AddHeading" class="btn btn-primary">Yeni Başlık Girişi</a>